name: Testing - Reusable Workflow
on: 
  workflow_call:
    inputs:
      ingress-url:
          description: Provide the Ingress URL
          required: true
          type: string
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - env:
         URL: ${{ inputs.ingress-url }}
        run: |
          echo "Testing URL: https://$URL/live"
          RESPONSE=$(curl -s -k https://$URL/live)
          echo "Response: $RESPONSE"
          echo "$RESPONSE" | jq . || echo "Invalid JSON response"
          echo "$RESPONSE" | jq -r .status | grep -i live
    