name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

  dev-deploy:
    environment: development
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0'

      - name: Debug Kubernetes Connection
        run: kubectl cluster-info

      - name: Verify Kubectl Installation
        run: kubectl version -o yaml

  integration-test:
    needs: dev-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Reusable Workflow
        uses: ./.github/workflows/reusable-workflow.yml
        with:
          ingress-url: "example.com"
