name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  integration-test:
    uses: elissianashaat/github-actions-solar-system/.github/workflows/reusable-workflow.yml@main  # ✅ Correct call
    with:
      ingress-url: "example.com"
