name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

  dev-deploy:
    environment: development
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0'

      - name: Set Kube Context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Verify Kubectl Installation
        run: kubectl version --short -o yaml
  # dev-deploy job
  integration-test:
   needs: dev-deploy
   uses: ./.github/workflows/reusable-workflow.yml
   with:
    ingress-url: ${{ needs.dev-deploy.outputs.APP_INGRESS_URL }}
# next job
