name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

  dev-deploy:
    environment: development
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0'

      - name: Set Kube Context
        uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: |
            apiVersion: v1
            kind: Config
            clusters:
              - name: my-cluster
                cluster:
                  server: https://your-kubernetes-server
            contexts:
              - name: my-context
                context:
                  cluster: my-cluster
                  user: my-user
            current-context: my-context
            users:
              - name: my-user
                user:
                  token: your-auth-token

      - name: Verify Kubectl Installation
        run: kubectl version -o yaml

  integration-test:
    needs: dev-deploy
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      ingress-url: "example.com"
